name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x] # Specify the Node.js versions you want to test against

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Check files
              run: |
                  echo "CommonJS files:"
                  ls dist/commonjs
                  echo "ESM files:"
                  ls dist/esm
