name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                node-version: [14.x, 16.x, 18.x, 20.x]
                exclude:
                    - os: windows-latest
                      node-version: 14.x

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install pcsclite
              run: sudo apt-get install -y libpcsclite1 libpcsclite-dev pcscd
              if: matrix.os == 'ubuntu-latest'

            - name: Install dependencies
              run: npm install

            - name: Build dist
              run: npm run build

            - name: Check files
              run: |
                  echo "CommonJS files:"
                  ls dist/commonjs
                  echo "ESM files:"
                  ls dist/esm
