name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # This enables manual triggering of the workflow

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        node-version: [ 14.x, 16.x, 18.x ]  # Updated Node.js versions
        exclude:
          # Exclude certain OS and Node.js version combinations if necessary
          # Add any excludes here if needed

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install pcsclite
        run: sudo apt-get install -y libpcsclite1 libpcsclite-dev pcscd
        if: matrix.os == 'ubuntu-latest'

      - name: Install dependencies
        run: npm install --verbose

      - name: Build dist
        run: npm run build

      - name: Check files
        run: |
            echo "CommonJS files:"
            ls dist/commonjs
            echo "ESM files:"
            ls dist/esm
        # This step replaces the original test steps, as per your build.yml
